[package]
name = "equation_processor"
version = "0.1.0"
edition = "2021"

[dependencies]
regex = "1.11.1"
clap = { version = "4.5.23", features = ["derive"] }
indicatif = "0.17"

[dev-dependencies]
assert_cmd = "2"
predicates = "3"
equation_processor = { path = "."}
